
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 52914
 */
public class ConversorMoneda extends javax.swing.JFrame {

    /**
     * Creates new form ConvertidorMoneda
     */
    public ConversorMoneda() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Conversor de Moneda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SelectMoneda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnCambiar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Conversor de Moneda");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elige la moneda a la cual deseas hacer la conversión:");

        SelectMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Peso a Dólar", "Dólar a Peso", "Peso a Euro", "Euro a Peso", "Peso a Libra", "Libra a Peso", "Peso a Yen", "Yen a Peso", "Peso a Won", "Won a Peso", "Peso a Peso Argentino", "Peso Argentino a Peso", "Peso a Sol Peruano", "Sol Peruano a Peso" }));
        SelectMoneda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SelectMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectMonedaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Digite la cantidad que desea cambiar:");

        txtCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        btnCambiar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCambiar.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiar.setText("Convertir");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCantidad))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(SelectMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnCambiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(SelectMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnCambiar)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    /*public double ImprimirValorPesoaOtro(double valor){
        double peso = 1;
        double resultado = peso * valor;
        return resultado;
    }*/

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed

        String select = (String) SelectMoneda.getSelectedItem().toString();
        String valor = txtCantidad.getText();
        double val = Double.parseDouble(valor);
        double peso = 1;
        double resultado = 0;

        if (select.equals("Selecciona")) {
            JOptionPane.showMessageDialog(null, "ERROR, Selecciona una moneda", "Atencion", JOptionPane.WARNING_MESSAGE);

        } else {

            //ponerle un try catch
            if (select.equals("Peso a Dólar")) {
                double dolar = 0.058;
                resultado = val * dolar;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " dolares");

            }
            if (select.equals("Dólar a Peso")) {
                peso = 17;
                resultado = val * peso;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " pesos");
            }
            if (select.equals("Peso a Euro")) {
                double euro = 0.053;
                resultado = val * euro;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " euros");
            }
            if (select.equals("Euro a Peso")) {
                peso = 18.85;
                resultado = val * peso;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " pesos");
            }
            if (select.equals("Peso a Libra")) {
                double libra = 0.045;
                resultado = val * libra;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " lbras");
            }
            if (select.equals("Libra a Peso")) {
                peso = 22.02;
                resultado = val * peso;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " pesos");
            }
            if (select.equals("Peso a Yen")) {
                double yen = 8.29;
                resultado = val * yen;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " yen");
            }
            if (select.equals("Yen a Peso")) {
                peso = 0.12;
                resultado = val * peso;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " pesos");
            }
            if (select.equals("Peso a Won")) {
                double won = 75.72;
                resultado = val * won;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " won");
            }
            if (select.equals("Won a Peso")) {
                peso = 0.013;
                resultado = val * peso;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " pesos");
            }
            if (select.equals("Peso a Peso Argentino")) {
                double pesoArg = 15.05;
                resultado = val * pesoArg;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " pesos argentinos");
            }
            if (select.equals("Peso Argentino a Peso")) {
                peso = 0.066;
                resultado = val * peso;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " pesos");
            }
            if (select.equals("Peso a Sol Peruano")) {
                double sol = 0.21;
                resultado = val * sol;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " soles peruanos");
            }
            if (select.equals("Sol Peruano a Peso")) {
                peso = 4.75;
                resultado = val * peso;
                JOptionPane.showMessageDialog(null, "Tienes " + resultado + " pesos");
            }

            //MENSAJE POR VENTANA EMERGENTE DE SI DESEA CONTINUAR Y LO REGRESA A LA SELECCION DE MONEDA POR SI DICE QUE SI
            //SI DICE QUE NO, CUADRO DE FINALIZO PROGRAMA
            int salir = (JOptionPane.showConfirmDialog(null, "¿Desea Continuar?"));

            if (salir == 0) {
                /*
                JOptionPane.showMessageDialog(null, "Por favor, Continúe...");
                SelectMoneda.setSelectedItem("Selecciona");
                txtCantidad.setText("");
                 */
                dispose();
                Conversor conv = new Conversor();
                conv.setVisible(true);

            } else if (salir == 1) {
                JOptionPane.showMessageDialog(null, "Programa Finalizado");
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(null, "Programa Finalizado");
                System.exit(0);
            }
        }


    }//GEN-LAST:event_btnCambiarActionPerformed


    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
        Conversor conv = new Conversor();
        conv.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void SelectMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectMonedaActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Valor Inválido, Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorMoneda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorMoneda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorMoneda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorMoneda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorMoneda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelectMoneda;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
